# Generated by Django 3.2.9 on 2022-02-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addEmployee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('position', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('contact', models.CharField(max_length=12)),
                ('date_of_birth', models.DateField(default=None)),
                ('national_id', models.CharField(default=None, max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('address', models.TextField(max_length=200)),
                ('is_employee', models.BooleanField(default=None)),
                ('is_employer', models.BooleanField(default=None)),
            ],
        ),
    ]
