# Generated by Django 3.2.9 on 2022-02-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220212_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='details',
        ),
        migrations.AddField(
            model_name='profile',
            name='signup_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
